version: '3.9'

services:
  backend:
    build:
      context: api-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TMDB_API_KEY=$TMDB_API_KEY
    restart: always

  frontend:
    container_name: nextjs_app
    build:
      context: webfront
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - TMDB_API_KEY=$TMDB_API_KEY
    depends_on:
      - backend
    restart: on-failure
